server:
  port: 3000
spring:
  datasource:
    name: xiaomi
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  # Redis 配置
  redis:
    host:
    port:
    database:
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接数
        min-idle: 0
        # 连接池中的最大空闲连接数
        max-idle: 8
        # 连接池的最大活跃连接数
        max-active: 8
        # 连接池最大阻塞等待时间，使用 PT 表示 Duration 格式
        max-wait: -1ms
jackson:
  date-format: yyyy-MM-dd HH:mm:ss

rabbitmq:
  host: localhost
  port: 5672   # 默认端口
  username: guest
  password: guest


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    org.apache.ibatis: DEBUG
#    com.mall.xiaomi: DEBUG
